CREATE DATABASE Biblioteca;
CREATE TABLE Aluno(
  AId INT(4) AUTO_INCREMENT,
  Nome VARCHAR(80) NOT NULL,
  CPF VARCHAR(14) NOT NULL,
  email VARCHAR(50) NOT NULL,
  PRIMARY KEY(AId)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);
CREATE TABLE Livro(
  ISBN VARCHAR(13) NOT NULL,
  Titulo VARCHAR(80) NOT NULL,
  Autor VARCHAR(80) NOT NULL,
  PRIMARY KEY(ISBN)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);
