CREATE DATABASE Biblioteca;
CREATE TABLE Aluno(
  AId INT(4) NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(80) NOT NULL,
  CPF VARCHAR(14) NOT NULL,
  email VARCHAR(50) NOT NULL,
  PRIMARY KEY(AId)
);
CREATE TABLE Livro(
  ISBN VARCHAR(13) NOT NULL,
  Titulo VARCHAR(80) NOT NULL,
  Autor VARCHAR(80) NOT NULL,
  PRIMARY KEY(ISBN)
);
CREATE TABLE Retira(
  Id INT(4) NOT NULL AUTO_INCREMENT,
  Data DATE NOT NULL,
  aluno INT(4) NOT NULL,
  livro VARCHAR(13) NOT NULL,
  PRIMARY KEY(Id)
  FOREIGN KEY (aluno)
    REFERENCES Aluno(AId)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
  FOREIGN KEY (livro)
    REFERENCES Livro(ISBN)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
